use_frameworks!

platform :ios, '9.0'

target 'TestLib_Example' do
  pod 'TestLib', :path => '../'

  target 'TestLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
